### Getting started with Keras

Keras is high-level API wriiten in python. <br>
since it is written in python so, it can be run on any operating system like Windows , linux or mac.

## Procesing Data 

In [1]:
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler 

In [2]:
train_lables = []
train_sample = []

Example Data 
* An experimental drug was tested from individual ages between 13 to 65.
* The trial had 2100 participants. Half were under 65 and half were above 65 .
* 95% of patients 65 or older have experinced side effects .
* 95% of patients below than 65 haven't experienced side effects .

### Getting raw data :


In [3]:
for i in range(1000):
    random_younger = randint(13,64)
    train_sample.append(random_younger)
    train_lables.append(0)
    
    random_older = randint(65,100)
    train_sample.append(random_older)
    train_lables.append(1)

for i in range(50):
    random_younger = randint(13,64)
    train_sample.append(random_younger)
    train_lables.append(1)
    
    random_older = randint(65,100)
    train_sample.append(random_older)
    train_lables.append(0)

In [4]:
#print raw data 
for i in train_sample:
    print(i)

52
94
17
91
31
90
51
88
36
81
39
75
35
91
52
85
39
71
46
78
45
84
19
71
63
77
16
87
52
93
41
97
28
87
27
83
40
93
45
67
21
68
35
68
38
88
17
97
44
65
60
76
39
80
58
81
13
67
56
87
23
91
40
88
28
77
29
78
17
97
56
100
62
78
44
84
58
85
63
94
62
90
63
67
40
89
49
94
24
65
35
100
36
77
18
90
54
66
41
76
30
80
64
89
59
76
23
92
18
91
16
67
13
80
32
87
48
65
20
88
40
68
61
93
15
88
24
83
14
71
50
86
32
91
59
87
62
85
22
81
46
84
49
98
51
91
29
80
31
87
47
87
54
82
38
96
23
98
35
82
43
97
34
86
19
94
32
67
64
69
34
91
50
71
55
83
49
95
59
78
25
93
43
95
31
88
45
66
29
100
34
72
15
100
14
67
49
69
31
88
30
95
60
98
46
66
33
76
60
80
61
70
28
81
13
67
54
70
31
90
14
78
33
90
26
82
62
76
51
68
23
84
17
81
52
87
36
69
28
73
23
71
18
85
25
77
22
98
46
97
55
90
24
65
34
89
13
73
27
89
48
84
36
83
29
80
41
90
14
82
46
65
30
89
35
86
25
70
21
92
50
70
23
79
47
84
18
91
50
80
39
76
59
84
15
65
27
86
64
73
41
95
25
77
39
95
29
85
39
68
28
82
50
73
26
81
21
73
26
72
22
81
24
82
39
85
38
95
33
74
50
78


In [5]:
for i in train_lables:
    print(i)

0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1


In [6]:
train_sample = np.array(train_sample)
train_lables = np.array(train_lables)

In [7]:
scaler = MinMaxScaler()
scaled_train_sample = scaler.fit_transform((train_sample).reshape(-1,1))

C:\Users\Aksha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [8]:
scaled_train_sample

array([[0.44827586],
       [0.93103448],
       [0.04597701],
       ...,
       [0.79310345],
       [0.56321839],
       [0.90804598]])

In [9]:
1+9

10

In [10]:
import keras
from keras import backend as k
from keras.models import Sequential
from keras.layers  import Activation
from keras.layers.core import Dense
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy

Using TensorFlow backend.


In [11]:
#model = Sequential([l1,l2,l3])
model = Sequential([Dense(16, input_shape=(1,), activation='relu'),
                  Dense(32, activation='relu'), Dense(2, activation='softmax')])

Instructions for updating:
Colocations handled automatically by placer.


In [12]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(Adam(lr=.0001), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

### Validation set 

In [14]:
model.fit(scaled_train_sample, train_lables,validation_split=0.1, batch_size=10, epochs=20, shuffle=True, verbose=2)

Instructions for updating:
Use tf.cast instead.
Train on 1890 samples, validate on 210 samples
Epoch 1/20
 - 1s - loss: 0.6500 - acc: 0.5508 - val_loss: 0.6997 - val_acc: 0.5190
Epoch 2/20
 - 0s - loss: 0.6256 - acc: 0.6587 - val_loss: 0.7041 - val_acc: 0.4952
Epoch 3/20
 - 0s - loss: 0.5980 - acc: 0.7339 - val_loss: 0.7109 - val_acc: 0.5000
Epoch 4/20
 - 0s - loss: 0.5673 - acc: 0.7656 - val_loss: 0.7195 - val_acc: 0.5095
Epoch 5/20
 - 0s - loss: 0.5338 - acc: 0.8032 - val_loss: 0.7297 - val_acc: 0.5143
Epoch 6/20
 - 0s - loss: 0.4987 - acc: 0.8434 - val_loss: 0.7453 - val_acc: 0.5143
Epoch 7/20
 - 0s - loss: 0.4627 - acc: 0.8714 - val_loss: 0.7639 - val_acc: 0.5000
Epoch 8/20
 - 0s - loss: 0.4270 - acc: 0.8910 - val_loss: 0.7831 - val_acc: 0.4952
Epoch 9/20
 - 0s - loss: 0.3928 - acc: 0.9090 - val_loss: 0.8093 - val_acc: 0.5000
Epoch 10/20
 - 0s - loss: 0.3606 - acc: 0.9196 - val_loss: 0.8421 - val_acc: 0.5048
Epoch 11/20
 - 0s - loss: 0.3308 - acc: 0.9249 - val_loss: 0.8739 - val_ac

### Prediction Set

In [16]:
test_sample = []
test_lables = []

In [17]:
for i in range(200):
    random_younger = randint(13,64)
    test_sample.append(random_younger)
    test_lables.append(0)
    
    random_older = randint(65,100)
    test_sample.append(random_older)
    test_lables.append(1)

for i in range(10):
    random_younger = randint(13,64)
    test_sample.append(random_younger)
    test_lables.append(1)
    
    random_older = randint(65,100)
    test_sample.append(random_older)
    test_lables.append(0)

In [19]:
test_sample = np.array(test_sample)

In [21]:
scaled_test_sample = scaler.fit_transform((test_sample).reshape(-1,1))

C:\Users\Aksha\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [22]:
prediction = model.predict(scaled_test_sample, batch_size= 10, verbose=0)

In [23]:
for i in prediction:
    print(i)

[0.9041931  0.09580693]
[0.15785007 0.8421499 ]
[0.9514874  0.04851263]
[0.02647447 0.9735256 ]
[0.85441726 0.14558272]
[0.04313155 0.9568684 ]
[0.6415489  0.35845113]
[0.02157438 0.97842556]
[0.9521016 0.0478984]
[0.25340727 0.7465927 ]
[0.9521016 0.0478984]
[0.01881264 0.98118734]
[0.43801683 0.56198317]
[0.03857959 0.96142036]
[0.9503955  0.04960452]
[0.4090311 0.5909689]
[0.9517805  0.04821951]
[0.30090216 0.6990979 ]
[0.9139986  0.08600137]
[0.30090216 0.6990979 ]
[0.95183897 0.04816109]
[0.14269665 0.8573034 ]
[0.6415489  0.35845113]
[0.14269665 0.8573034 ]
[0.742141   0.25785905]
[0.1160287 0.8839713]
[0.46743217 0.53256774]
[0.03498382 0.9650162 ]
[0.9309248 0.0690752]
[0.04313155 0.9568684 ]
[0.8933999  0.10660009]
[0.07546517 0.92453486]
[0.49707553 0.50292444]
[0.05406972 0.94593024]
[0.9517805  0.04821951]
[0.2111449  0.78885514]
[0.5267396  0.47326043]
[0.17428552 0.8257145 ]
[0.9495162  0.05048378]
[0.30090216 0.6990979 ]
[0.76420695 0.23579307]
[0.04830759 0.9516924 ]
[0

In [24]:
rounded_prediction = model.predict_classes(scaled_test_sample, batch_size=10, verbose=0)

In [25]:
for i in rounded_prediction:
    print(i)

0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
1
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1


### Confusion Matrix

In [27]:
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline

import itertools 


In [29]:
cm = confusion_matrix(test_lables, rounded_prediction)

In [31]:
cm

array([[190,  20],
       [ 10, 200]], dtype=int64)

* TN = 190
* FN = 10
* FP = 20
* TP = 200

### Model Save

In [32]:
model.save('medical_trial_model.h5')

In [36]:
from keras.models import load_model
new_model = load_model('medical_trial_model.h5')

This model save the whole same the previous model<br>
Let's see :

In [38]:
new_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_2 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [39]:
new_model.get_weights()

[array([[-0.3957496 , -0.5327849 , -0.25334695,  0.2677706 ,  0.43265182,
         -0.00686395, -0.4311123 ,  0.4745348 ,  0.5171079 , -0.5038901 ,
         -0.3092473 , -0.4056967 , -0.07615083, -0.32364348, -0.18596444,
          0.65377027]], dtype=float32),
 array([ 0.        ,  0.        ,  0.        , -0.02165855, -0.11930187,
         0.        ,  0.        , -0.13233356, -0.02918091,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.13367602], dtype=float32),
 array([[-3.23521495e-01,  3.03121477e-01, -1.48561567e-01,
          3.40491831e-02,  2.46019572e-01, -7.12140203e-02,
         -2.29184270e-01, -1.63716733e-01,  2.06260175e-01,
          2.64643937e-01,  8.16467106e-02,  1.95647478e-02,
         -3.26749504e-01,  8.91265869e-02, -1.93417624e-01,
          3.23940247e-01,  1.73988849e-01, -1.03756860e-01,
         -1.58460349e-01,  2.71128207e-01, -2.61729717e-01,
         -2.43789345e-01,  3.51076424e-02, -1.24353513e-01,
 

In [40]:
new_model.optimizer